Repository jimasr/bytecites, pull requests merged in 2023-04, with the labels that each got.

#16 Merge Post to Develop
  assets/styles/app.scss
  assets/styles/component/_comment.scss
  assets/styles/component/_post.scss
  assets/styles/template/_post.scss
  composer.lock
  src/Controller/CommentController.php
  src/Controller/PostController.php
  src/Entity/Category.php
  src/Entity/Post.php
  src/Form/CommentType.php
  src/Form/PostType.php
  templates/base/header.html.twig
  templates/category/index.html.twig
  templates/category/show.html.twig
  templates/comment/_form.html.twig
  templates/component/comment.post.html.twig
  templates/component/home.post.html.twig
  templates/post/index.html.twig
  templates/post/show.html.twig
Labels: feature, help wanted, front-end, back-end

#17 Add search functionality and its implementation
  assets/images/icons/search.png
  src/Controller/PostController.php
  src/Controller/SearchController.php
  src/Repository/PostRepository.php
  templates/base/header.html.twig
  templates/home/index.html.twig
  templates/search/index.html.twig
Labels: feature, back-end, bonus

#21 Logic post
  src/Controller/CategoryController.php
  src/Controller/HomeController.php
  src/Controller/SearchController.php
  src/Repository/PostRepository.php
  templates/base/header.html.twig
  templates/category/_categories.html.twig
  templates/category/show.html.twig
  templates/home/index.html.twig
  templates/home/latest.html.twig
  templates/home/popular.html.twig
Labels: documentation, feature, back-end

#23 Login
  assets/styles/app.scss
  assets/styles/base/_login.scss
  assets/styles/base/_register.scss
  assets/styles/layout/_header.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  src/Controller/HomeController.php
  src/Controller/RegistrationController.php
  src/Controller/SearchController.php
  src/Controller/SecurityController.php
  src/Form/LoginFormType.php
  src/Form/RegistrationFormType.php
  src/Security/LoginFormAuthenticator.php
  templates/base/header.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/security/index.html.twig
  templates/security/login.html.twig
Labels: good first issue, back-end, bonus

#26 User upgrade
  .gitignore
  assets/images/user/default_user.png
  assets/styles/app.scss
  assets/styles/base/_settings.scss
  assets/styles/base/_user.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/liip_imagine.yaml
  config/packages/vich_uploader.yaml
  config/routes/liip_imagine.yaml
  package-lock.json
  package.json
  src/Controller/Admin/PostController.php
  src/Controller/HomeController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/UserType.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/admin/post/new.html.twig
  templates/admin/user/index.html.twig
  templates/base/header.html.twig
  templates/post/show.html.twig
  templates/security/settings.html.twig
  translations/security.en.yaml
Labels: feature, back-end, bonus

#28 Readme completed
  README.md
Labels: documentation, help wanted

#29 Patch UI
  assets/styles/base/_settings.scss
  templates/admin/admin/index.html.twig
  templates/admin/category/index.html.twig
  templates/admin/post/index.html.twig
  templates/admin/user/index.html.twig
  templates/base/admin.header.html.twig
  templates/base/header.html.twig
  templates/security/settings.html.twig
Labels: front-end
